name: build-release-dev-vpc

on: [workflow_dispatch]

jobs:
    build:
        runs-on: unbuntu-latest

    steps:
        # Check out repo 
        - name:
          uses:  
        
        # Configure AWS Credentials
        - name: 
          uses:
          with:
            aws-access-key-id: ${{}}
            aws-secret-access-key: ${{}}
            aws-region: ${{}}
        
        # Setup Terraform 
        - name: 
          uses:
       
        # Deploy/Redeploy Infrastructure 
        - name:
          working-directory:
          run: |
