name: destroy-dev-vpc

on: [workflow_dispatch]

jobs:
    build:
        runs-on: unbuntu-latest

        steps:
          # Check out repo
          - name: Git Checkout
            uses: actions/checkout@v4

          # Configure AWS Credentials
          - name: Configure AWS Credentials
            uses: aws-actions/configure-aws-credentials@v4
            with:
                aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
                aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
                aws-region: ${{ vars.AWS_REGION }}

          # Setup Terraform
          - name: Setup Terraform
            uses: hashicorp/setup-terraform@v3
           
         # Destroy Terraform
          - name: Destroy Terraform
            working-directory: ./terraform
            run: |
              rm -fr terraform.tfstate || echo 'Does not exist'
              terraform init -input=flase
              terraform workspace new ${GITHUB_REF##*/} || echo 'Already exists'
              terraform workspace select ${GITHUB_REF##*/} && terraform destroy -input=false -auto-approve
          